/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interfaces;

import Clases.Expediente;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author Kevin
 */
public class IExpedientesQueVenceran extends javax.swing.JFrame {
Expediente exp = new Expediente();
    int dia;
    Date fecha;
    String mifecha = null;

    /**
     * Creates new form IExpedientesQueVenceran
     */
    public IExpedientesQueVenceran() {
        initComponents();
        llenarIntervalo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtImprimir = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVencimiento = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        cbIntervalo = new javax.swing.JComboBox();
        txtGenerar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("EXPEDIENTES QUE VENCERAN");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("EXPEDIENTES QUE VENCERÁN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        jLabel11.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel11.setText("Fecha desde");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, -1, -1));

        txtImprimir.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        txtImprimir.setText("Imprimir");
        getContentPane().add(txtImprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, -1, -1));

        jLabel12.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel12.setText("Intervalo");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, -1, -1));

        tblVencimiento.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        tblVencimiento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblVencimiento.setSelectionBackground(new java.awt.Color(255, 255, 168));
        jScrollPane1.setViewportView(tblVencimiento);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 174, 632, 310));

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/little logo.png"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 63, 67));

        jLabel6.setBackground(new java.awt.Color(47, 72, 85));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/top.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 70));

        jLabel14.setFont(new java.awt.Font("Cambria", 2, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(31, 33, 32));
        jLabel14.setText("Parámetros");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, -1, -1));

        jSeparator1.setFont(new java.awt.Font("Cambria", 0, 11)); // NOI18N
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 210, 10));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, 10, 60));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 630, 10));
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 170, -1));

        cbIntervalo.setEditable(true);
        cbIntervalo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbIntervalo.setToolTipText("Seleccione");
        getContentPane().add(cbIntervalo, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 140, 130, -1));

        txtGenerar1.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        txtGenerar1.setText("Generar");
        txtGenerar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGenerar1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtGenerar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 100, 80, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtGenerar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGenerar1ActionPerformed
        // TODO add your handling code here:
        fecha = jDateChooser1.getDate();
        SimpleDateFormat f = new SimpleDateFormat("yyyy-dd-MM");
        
        mifecha = f.format(fecha);
        //JOptionPane.showMessageDialog(null, "la fecha" + formato.format(fecha));

       
        if(cbIntervalo.getSelectedIndex() == 0){
            dia = 5;
        }else if(cbIntervalo.getSelectedIndex() == 1){
            dia = 10;
        }else if(cbIntervalo.getSelectedIndex() == 2){
            dia = 15;
        }
        datos();
        // JOptionPane.showMessageDialog(null, "el dia" + dia);

    }//GEN-LAST:event_txtGenerar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IExpedientesQueVenceran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IExpedientesQueVenceran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IExpedientesQueVenceran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IExpedientesQueVenceran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IExpedientesQueVenceran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbIntervalo;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable tblVencimiento;
    private javax.swing.JButton txtGenerar1;
    private javax.swing.JButton txtImprimir;
    // End of variables declaration//GEN-END:variables

    public void llenarIntervalo(){
        cbIntervalo.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"5", "10", "15" }));
    }

    public void datos(){
        
        tblVencimiento.setModel(exp.consultarVencimiento(mifecha, dia));
        //tblVencimiento.setModel(exp.consultarVencimiento("20100101", dia));
    }
}