/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interfaces;

import Clases.Expediente;
import Clases.Mapa;
import Controlador.Validar;
import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import sun.util.calendar.LocalGregorianCalendar.Date;

/**
 *
 * @author Kevin
 */
public class MapaDeDenuncias extends javax.swing.JFrame {
    Expediente exp = new Expediente();
    
    /**
     * Creates new form MapaDeDenuncias
     */
    public MapaDeDenuncias() {
        initComponents();
          datos();
          cargarLista();
    }
    
    public void cargarDatosMapa(){
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblMapa = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        santaana = new javax.swing.JLabel();
        chalatenango = new javax.swing.JLabel();
        sonsonate = new javax.swing.JLabel();
        lalibertad = new javax.swing.JLabel();
        lapaz = new javax.swing.JLabel();
        usulutan = new javax.swing.JLabel();
        sanmiguel = new javax.swing.JLabel();
        sanvicente = new javax.swing.JLabel();
        morazan = new javax.swing.JLabel();
        cabañas = new javax.swing.JLabel();
        sansalvador = new javax.swing.JLabel();
        cuscatlan = new javax.swing.JLabel();
        auachapan = new javax.swing.JLabel();
        launion = new javax.swing.JLabel();
        jLabel_mapa = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MAPA DE DENUNCIAS");

        tblMapa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblMapa);

        jLabel2.setBackground(new java.awt.Color(47, 72, 85));
        jLabel2.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("MAPA DE DENUNCIAS POR DEPARTAMENTO Y FECHA");
        jLabel2.setOpaque(true);

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        santaana.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        santaana.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        santaana.setText("<html><center>departamento <br> N# denuncias <br> N# omitidas <br> N# admitidas</center> </html>");
        jPanel3.add(santaana, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 110, 100));

        chalatenango.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        chalatenango.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chalatenango.setText("<html><center>departamento <br> N# denuncias <br> N# omitidas <br> N# admitidas</center> </html>");
        jPanel3.add(chalatenango, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 110, 100));

        sonsonate.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        sonsonate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sonsonate.setText("<html><center>departamento <br> N# denuncias <br> N# omitidas <br> N# admitidas</center> </html>");
        jPanel3.add(sonsonate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 110, 100));

        lalibertad.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        lalibertad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lalibertad.setText("<html><center>departamento <br> N# denuncias <br> N# omitidas <br> N# admitidas</center> </html>");
        jPanel3.add(lalibertad, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 110, 100));

        lapaz.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        lapaz.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lapaz.setText("<html><center>departamento <br> N# denuncias <br> N# omitidas <br> N# admitidas</center> </html>");
        jPanel3.add(lapaz, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 110, 100));

        usulutan.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        usulutan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usulutan.setText("<html><center>departamento <br> N# denuncias <br> N# omitidas <br> N# admitidas</center> </html>");
        jPanel3.add(usulutan, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, 110, 100));

        sanmiguel.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        sanmiguel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sanmiguel.setText("<html><center>departamento <br> N# denuncias <br> N# omitidas <br> N# admitidas</center> </html>");
        jPanel3.add(sanmiguel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, 110, 100));

        sanvicente.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        sanvicente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sanvicente.setText("<html><center>departamento <br> N# denuncias <br> N# omitidas <br> N# admitidas</center> </html>");
        jPanel3.add(sanvicente, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, 110, 100));

        morazan.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        morazan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        morazan.setText("<html><center>departamento <br> N# denuncias <br> N# omitidas <br> N# admitidas</center> </html>");
        jPanel3.add(morazan, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, 110, 100));

        cabañas.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        cabañas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cabañas.setText("<html><center>departamento <br> N# denuncias <br> N# omitidas <br> N# admitidas</center> </html>");
        jPanel3.add(cabañas, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 110, 100));

        sansalvador.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        sansalvador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sansalvador.setText("<html><center>departamento <br> N# denuncias <br> N# omitidas <br> N# admitidas</center> </html>");
        jPanel3.add(sansalvador, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 110, 100));

        cuscatlan.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        cuscatlan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cuscatlan.setText("<html><center>departamento <br> N# denuncias <br> N# omitidas <br> N# admitidas</center> </html>");
        jPanel3.add(cuscatlan, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 110, 100));

        auachapan.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        auachapan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        auachapan.setText("<html><center>departamento <br> N# denuncias <br> N# omitidas <br> N# admitidas</center> </html>");
        jPanel3.add(auachapan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 110, 100));

        launion.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        launion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        launion.setText("<html><center>departamento <br> N# denuncias <br> N# omitidas <br> N# admitidas</center> </html>");
        jPanel3.add(launion, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 290, 110, 100));

        jLabel_mapa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_mapa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ElSalvador.PNG"))); // NOI18N
        jPanel3.add(jLabel_mapa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 390));

        jButton1.setText("Informe");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Fecha inicio: ");

        jLabel3.setText("Fecha fin: ");

        jDateChooser1.setDate(new java.util.Date(788940000000L));
        jDateChooser1.setDateFormatString("dd-MM-yyyy");
        jDateChooser1.setMaxSelectableDate(new java.util.Date(1577862115000L));
        jDateChooser1.setMinSelectableDate(new java.util.Date(788943715000L));

        jDateChooser2.setDate(new java.util.Date(1451628000000L));
        jDateChooser2.setDateFormatString("dd-MM-yyyy");
        jDateChooser2.setMaxSelectableDate(new java.util.Date(1577862115000L));
        jDateChooser2.setMinSelectableDate(new java.util.Date(788943715000L));

        jButton2.setText("Consultar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setText("Departamento");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jDateChooser2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
        
        datosPorFecha();
        cargarTabla();
        /*java.util.Date fechax = jDateChooser1.getDate();
        SimpleDateFormat f = new SimpleDateFormat("yyyy-MM-dd");
        JOptionPane.showMessageDialog(null, f.format(fechax).toString());*/
        
        
      
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MapaDeDenuncias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MapaDeDenuncias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MapaDeDenuncias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MapaDeDenuncias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MapaDeDenuncias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel auachapan;
    private javax.swing.JLabel cabañas;
    private javax.swing.JLabel chalatenango;
    private javax.swing.JLabel cuscatlan;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel_mapa;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lalibertad;
    private javax.swing.JLabel lapaz;
    private javax.swing.JLabel launion;
    private javax.swing.JLabel morazan;
    private javax.swing.JLabel sanmiguel;
    private javax.swing.JLabel sansalvador;
    private javax.swing.JLabel santaana;
    private javax.swing.JLabel sanvicente;
    private javax.swing.JLabel sonsonate;
    private javax.swing.JTable tblMapa;
    private javax.swing.JLabel usulutan;
    // End of variables declaration//GEN-END:variables

private void datos(){
        
        Mapa m = new Mapa();
        
        JTable table = new JTable(m.consultarDenunciasPorDepartamentoTotal("SANTA ANA"));
        santaana.setText("<html><center>"+table.getModel().getValueAt(0, 0).toString()+"<br>"+
                               "denuncias: "+table.getModel().getValueAt(0, 1).toString()+"<br>"+
                               "jueces: "+table.getModel().getValueAt(0, 2).toString()+"<br>"+
                               table.getModel().getValueAt(0, 3).toString()+" admitidas<br>"+
                               table.getModel().getValueAt(0, 4).toString()+" omitidas<br>"+
                               table.getModel().getValueAt(0, 5).toString()+" otras<br>"+
                               "</center></html>");
        
        table = new JTable(m.consultarDenunciasPorDepartamentoTotal("AHUACHAPAN"));
        auachapan.setText("<html><center>"+table.getModel().getValueAt(0, 0).toString()+"<br>"+
                               "denuncias: "+table.getModel().getValueAt(0, 1).toString()+"<br>"+
                               "jueces: "+table.getModel().getValueAt(0, 2).toString()+"<br>"+
                               table.getModel().getValueAt(0, 3).toString()+" admitidas<br>"+
                               table.getModel().getValueAt(0, 4).toString()+" omitidas<br>"+
                               table.getModel().getValueAt(0, 5).toString()+" otras<br>"+
                               "</center></html>");
        
        table = new JTable(m.consultarDenunciasPorDepartamentoTotal("SONSONATE"));
        sonsonate.setText("<html><center>"+table.getModel().getValueAt(0, 0).toString()+"<br>"+
                               "denuncias: "+table.getModel().getValueAt(0, 1).toString()+"<br>"+
                               "jueces: "+table.getModel().getValueAt(0, 2).toString()+"<br>"+
                               table.getModel().getValueAt(0, 3).toString()+" admitidas<br>"+
                               table.getModel().getValueAt(0, 4).toString()+" omitidas<br>"+
                               table.getModel().getValueAt(0, 5).toString()+" otras<br>"+
                               "</center></html>");
        
        table = new JTable(m.consultarDenunciasPorDepartamentoTotal("LA LIBERTAD"));
        lalibertad.setText("<html><center>"+table.getModel().getValueAt(0, 0).toString()+"<br>"+
                               "denuncias: "+table.getModel().getValueAt(0, 1).toString()+"<br>"+
                               "jueces: "+table.getModel().getValueAt(0, 2).toString()+"<br>"+
                               table.getModel().getValueAt(0, 3).toString()+" admitidas<br>"+
                               table.getModel().getValueAt(0, 4).toString()+" omitidas<br>"+
                               table.getModel().getValueAt(0, 5).toString()+" otras<br>"+
                               "</center></html>");
        
        table = new JTable(m.consultarDenunciasPorDepartamentoTotal("SAN SALVADOR"));
        sansalvador.setText("<html><center>"+table.getModel().getValueAt(0, 0).toString()+"<br>"+
                               "denuncias: "+table.getModel().getValueAt(0, 1).toString()+"<br>"+
                               "jueces: "+table.getModel().getValueAt(0, 2).toString()+"<br>"+
                               table.getModel().getValueAt(0, 3).toString()+" admitidas<br>"+
                               table.getModel().getValueAt(0, 4).toString()+" omitidas<br>"+
                               table.getModel().getValueAt(0, 5).toString()+" otras<br>"+
                               "</center></html>");
        
        table = new JTable(m.consultarDenunciasPorDepartamentoTotal("LA PAZ"));
        lapaz.setText("<html><center>"+table.getModel().getValueAt(0, 0).toString()+"<br>"+
                               "denuncias: "+table.getModel().getValueAt(0, 1).toString()+"<br>"+
                               "jueces: "+table.getModel().getValueAt(0, 2).toString()+"<br>"+
                               table.getModel().getValueAt(0, 3).toString()+" admitidas<br>"+
                               table.getModel().getValueAt(0, 4).toString()+" omitidas<br>"+
                               table.getModel().getValueAt(0, 5).toString()+" otras<br>"+
                               "</center></html>");
        
        table = new JTable(m.consultarDenunciasPorDepartamentoTotal("CUSCATLAN"));
        cuscatlan.setText("<html><center>"+table.getModel().getValueAt(0, 0).toString()+"<br>"+
                               "denuncias: "+table.getModel().getValueAt(0, 1).toString()+"<br>"+
                               "jueces: "+table.getModel().getValueAt(0, 2).toString()+"<br>"+
                               table.getModel().getValueAt(0, 3).toString()+" admitidas<br>"+
                               table.getModel().getValueAt(0, 4).toString()+" omitidas<br>"+
                               table.getModel().getValueAt(0, 5).toString()+" otras<br>"+
                               "</center></html>");
        
        table = new JTable(m.consultarDenunciasPorDepartamentoTotal("CABAÑAS"));
        cabañas.setText("<html><center>"+table.getModel().getValueAt(0, 0).toString()+"<br>"+
                               "denuncias: "+table.getModel().getValueAt(0, 1).toString()+"<br>"+
                               "jueces: "+table.getModel().getValueAt(0, 2).toString()+"<br>"+
                               table.getModel().getValueAt(0, 3).toString()+" admitidas<br>"+
                               table.getModel().getValueAt(0, 4).toString()+" omitidas<br>"+
                               table.getModel().getValueAt(0, 5).toString()+" otras<br>"+
                               "</center></html>");
        
        table = new JTable(m.consultarDenunciasPorDepartamentoTotal("SAN VICENTE"));
        sanvicente.setText("<html><center>"+table.getModel().getValueAt(0, 0).toString()+"<br>"+
                               "denuncias: "+table.getModel().getValueAt(0, 1).toString()+"<br>"+
                               "jueces: "+table.getModel().getValueAt(0, 2).toString()+"<br>"+
                               table.getModel().getValueAt(0, 3).toString()+" admitidas<br>"+
                               table.getModel().getValueAt(0, 4).toString()+" omitidas<br>"+
                               table.getModel().getValueAt(0, 5).toString()+" otras<br>"+
                               "</center></html>");
        
        table = new JTable(m.consultarDenunciasPorDepartamentoTotal("SAN MIGUEL"));
        sanmiguel.setText("<html><center>"+table.getModel().getValueAt(0, 0).toString()+"<br>"+
                               "denuncias: "+table.getModel().getValueAt(0, 1).toString()+"<br>"+
                               "jueces: "+table.getModel().getValueAt(0, 2).toString()+"<br>"+
                               table.getModel().getValueAt(0, 3).toString()+" admitidas<br>"+
                               table.getModel().getValueAt(0, 4).toString()+" omitidas<br>"+
                               table.getModel().getValueAt(0, 5).toString()+" otras<br>"+
                               "</center></html>");
        
        table = new JTable(m.consultarDenunciasPorDepartamentoTotal("LA UNION"));
        launion.setText("<html><center>"+table.getModel().getValueAt(0, 0).toString()+"<br>"+
                               "denuncias: "+table.getModel().getValueAt(0, 1).toString()+"<br>"+
                               "jueces: "+table.getModel().getValueAt(0, 2).toString()+"<br>"+
                               table.getModel().getValueAt(0, 3).toString()+" admitidas<br>"+
                               table.getModel().getValueAt(0, 4).toString()+" omitidas<br>"+
                               table.getModel().getValueAt(0, 5).toString()+" otras<br>"+
                               "</center></html>");
        
        table = new JTable(m.consultarDenunciasPorDepartamentoTotal("MORAZAN"));
        morazan.setText("<html><center>"+table.getModel().getValueAt(0, 0).toString()+"<br>"+
                               "denuncias: "+table.getModel().getValueAt(0, 1).toString()+"<br>"+
                               "jueces: "+table.getModel().getValueAt(0, 2).toString()+"<br>"+
                               table.getModel().getValueAt(0, 3).toString()+" admitidas<br>"+
                               table.getModel().getValueAt(0, 4).toString()+" omitidas<br>"+
                               table.getModel().getValueAt(0, 5).toString()+" otras<br>"+
                               "</center></html>");
        
        table = new JTable(m.consultarDenunciasPorDepartamentoTotal("CHALATENANGO"));
        chalatenango.setText("<html><center>"+table.getModel().getValueAt(0, 0).toString()+"<br>"+
                               "denuncias: "+table.getModel().getValueAt(0, 1).toString()+"<br>"+
                               "jueces: "+table.getModel().getValueAt(0, 2).toString()+"<br>"+
                               table.getModel().getValueAt(0, 3).toString()+" admitidas<br>"+
                               table.getModel().getValueAt(0, 4).toString()+" omitidas<br>"+
                               table.getModel().getValueAt(0, 5).toString()+" otras<br>"+
                               "</center></html>");
        
        table = new JTable(m.consultarDenunciasPorDepartamentoTotal("USULUTAN"));
        usulutan.setText("<html><center>"+table.getModel().getValueAt(0, 0).toString()+"<br>"+
                               "denuncias: "+table.getModel().getValueAt(0, 1).toString()+"<br>"+
                               "jueces: "+table.getModel().getValueAt(0, 2).toString()+"<br>"+
                               table.getModel().getValueAt(0, 3).toString()+" admitidas<br>"+
                               table.getModel().getValueAt(0, 4).toString()+" omitidas<br>"+
                               table.getModel().getValueAt(0, 5).toString()+" otras<br>"+
                               "</center></html>");
        
        
        }

private void cargarLista(){
    
    Mapa m = new Mapa();
    JTable table = new JTable(m.consultarDepartamentos()); 
    
    for(int i=0; i < table.getModel().getRowCount(); i++)
        jComboBox1.addItem(table.getModel().getValueAt(i, 1));

}

private void cargarTabla(){
    
    java.util.Date fecha1 = jDateChooser1.getDate();
    java.util.Date fecha2 = jDateChooser2.getDate();
    SimpleDateFormat f = new SimpleDateFormat("yyyy-dd-MM");
    Validar v = new Validar();
        
       if(v.validarFecha2MayorQueFecha1(fecha1, fecha2)){
    
        Mapa m = new Mapa();
        JTable table = new JTable(m.consultarDenunciasPorMunicipio(jComboBox1.getSelectedIndex(), f.format(fecha1).toString(), f.format(fecha2).toString())); 
        tblMapa.setModel(table.getModel());
    
       }

}


 private void datosPorFecha(){       
   
    
        java.util.Date fecha1 = jDateChooser1.getDate();
        java.util.Date fecha2 = jDateChooser2.getDate();
        SimpleDateFormat f = new SimpleDateFormat("yyyy-dd-MM");
        Validar v = new Validar();
        
       if(v.validarFecha2MayorQueFecha1(fecha1, fecha2)){
        
        
        
        Mapa m = new Mapa();
        
        
        JOptionPane.showMessageDialog(null, f.format(fecha1).toString() + f.format(fecha2).toString());
        JTable table = new JTable(m.consultarDenunciasPorDepartamento("SANTA ANA", f.format(fecha1).toString(), f.format(fecha2).toString()));    
        santaana.setText("<html><center>"+table.getModel().getValueAt(0, 0).toString()+"<br>"+
                               "denuncias: "+table.getModel().getValueAt(0, 1).toString()+"<br>"+
                               "jueces: "+table.getModel().getValueAt(0, 2).toString()+"<br>"+
                               table.getModel().getValueAt(0, 3).toString()+" admitidas<br>"+
                               table.getModel().getValueAt(0, 4).toString()+" omitidas<br>"+
                               table.getModel().getValueAt(0, 5).toString()+" otras<br>"+
                               "</center></html>");
        
        
        
        table = new JTable(m.consultarDenunciasPorDepartamento("AHUACHAPAN", f.format(fecha1).toString(), f.format(fecha2).toString()));
        auachapan.setText("<html><center>"+table.getModel().getValueAt(0, 0).toString()+"<br>"+
                               "denuncias: "+table.getModel().getValueAt(0, 1).toString()+"<br>"+
                               "jueces: "+table.getModel().getValueAt(0, 2).toString()+"<br>"+
                               table.getModel().getValueAt(0, 3).toString()+" admitidas<br>"+
                               table.getModel().getValueAt(0, 4).toString()+" omitidas<br>"+
                               table.getModel().getValueAt(0, 5).toString()+" otras<br>"+
                               "</center></html>");
        
        table = new JTable(m.consultarDenunciasPorDepartamento("SONSONATE", f.format(fecha1).toString(), f.format(fecha2).toString()));
        sonsonate.setText("<html><center>"+table.getModel().getValueAt(0, 0).toString()+"<br>"+
                               "denuncias: "+table.getModel().getValueAt(0, 1).toString()+"<br>"+
                               "jueces: "+table.getModel().getValueAt(0, 2).toString()+"<br>"+
                               table.getModel().getValueAt(0, 3).toString()+" admitidas<br>"+
                               table.getModel().getValueAt(0, 4).toString()+" omitidas<br>"+
                               table.getModel().getValueAt(0, 5).toString()+" otras<br>"+
                               "</center></html>");
        
        table = new JTable(m.consultarDenunciasPorDepartamento("LA LIBERTAD", f.format(fecha1).toString(), f.format(fecha2).toString()));
        lalibertad.setText("<html><center>"+table.getModel().getValueAt(0, 0).toString()+"<br>"+
                               "denuncias: "+table.getModel().getValueAt(0, 1).toString()+"<br>"+
                               "jueces: "+table.getModel().getValueAt(0, 2).toString()+"<br>"+
                               table.getModel().getValueAt(0, 3).toString()+" admitidas<br>"+
                               table.getModel().getValueAt(0, 4).toString()+" omitidas<br>"+
                               table.getModel().getValueAt(0, 5).toString()+" otras<br>"+
                               "</center></html>");
        
        table = new JTable(m.consultarDenunciasPorDepartamento("SAN SALVADOR", f.format(fecha1).toString(), f.format(fecha2).toString()));
        sansalvador.setText("<html><center>"+table.getModel().getValueAt(0, 0).toString()+"<br>"+
                               "denuncias: "+table.getModel().getValueAt(0, 1).toString()+"<br>"+
                               "jueces: "+table.getModel().getValueAt(0, 2).toString()+"<br>"+
                               table.getModel().getValueAt(0, 3).toString()+" admitidas<br>"+
                               table.getModel().getValueAt(0, 4).toString()+" omitidas<br>"+
                               table.getModel().getValueAt(0, 5).toString()+" otras<br>"+
                               "</center></html>");
        
        table = new JTable(m.consultarDenunciasPorDepartamento("LA PAZ", f.format(fecha1).toString(), f.format(fecha2).toString()));
        lapaz.setText("<html><center>"+table.getModel().getValueAt(0, 0).toString()+"<br>"+
                               "denuncias: "+table.getModel().getValueAt(0, 1).toString()+"<br>"+
                               "jueces: "+table.getModel().getValueAt(0, 2).toString()+"<br>"+
                               table.getModel().getValueAt(0, 3).toString()+" admitidas<br>"+
                               table.getModel().getValueAt(0, 4).toString()+" omitidas<br>"+
                               table.getModel().getValueAt(0, 5).toString()+" otras<br>"+
                               "</center></html>");
        
        table = new JTable(m.consultarDenunciasPorDepartamento("CUSCATLAN", f.format(fecha1).toString(), f.format(fecha2).toString()));
        cuscatlan.setText("<html><center>"+table.getModel().getValueAt(0, 0).toString()+"<br>"+
                               "denuncias: "+table.getModel().getValueAt(0, 1).toString()+"<br>"+
                               "jueces: "+table.getModel().getValueAt(0, 2).toString()+"<br>"+
                               table.getModel().getValueAt(0, 3).toString()+" admitidas<br>"+
                               table.getModel().getValueAt(0, 4).toString()+" omitidas<br>"+
                               table.getModel().getValueAt(0, 5).toString()+" otras<br>"+
                               "</center></html>");
        
        table = new JTable(m.consultarDenunciasPorDepartamento("CABAÑAS", f.format(fecha1).toString(), f.format(fecha2).toString()));
        cabañas.setText("<html><center>"+table.getModel().getValueAt(0, 0).toString()+"<br>"+
                               "denuncias: "+table.getModel().getValueAt(0, 1).toString()+"<br>"+
                               "jueces: "+table.getModel().getValueAt(0, 2).toString()+"<br>"+
                               table.getModel().getValueAt(0, 3).toString()+" admitidas<br>"+
                               table.getModel().getValueAt(0, 4).toString()+" omitidas<br>"+
                               table.getModel().getValueAt(0, 5).toString()+" otras<br>"+
                               "</center></html>");
        
        table = new JTable(m.consultarDenunciasPorDepartamento("SAN VICENTE", f.format(fecha1).toString(), f.format(fecha2).toString()));
        sanvicente.setText("<html><center>"+table.getModel().getValueAt(0, 0).toString()+"<br>"+
                               "denuncias: "+table.getModel().getValueAt(0, 1).toString()+"<br>"+
                               "jueces: "+table.getModel().getValueAt(0, 2).toString()+"<br>"+
                               table.getModel().getValueAt(0, 3).toString()+" admitidas<br>"+
                               table.getModel().getValueAt(0, 4).toString()+" omitidas<br>"+
                               table.getModel().getValueAt(0, 5).toString()+" otras<br>"+
                               "</center></html>");
        
        table = new JTable(m.consultarDenunciasPorDepartamento("SAN MIGUEL", f.format(fecha1).toString(), f.format(fecha2).toString()));
        sanmiguel.setText("<html><center>"+table.getModel().getValueAt(0, 0).toString()+"<br>"+
                               "denuncias: "+table.getModel().getValueAt(0, 1).toString()+"<br>"+
                               "jueces: "+table.getModel().getValueAt(0, 2).toString()+"<br>"+
                               table.getModel().getValueAt(0, 3).toString()+" admitidas<br>"+
                               table.getModel().getValueAt(0, 4).toString()+" omitidas<br>"+
                               table.getModel().getValueAt(0, 5).toString()+" otras<br>"+
                               "</center></html>");
        
        table = new JTable(m.consultarDenunciasPorDepartamento("LA UNION", f.format(fecha1).toString(), f.format(fecha2).toString()));
        launion.setText("<html><center>"+table.getModel().getValueAt(0, 0).toString()+"<br>"+
                               "denuncias: "+table.getModel().getValueAt(0, 1).toString()+"<br>"+
                               "jueces: "+table.getModel().getValueAt(0, 2).toString()+"<br>"+
                               table.getModel().getValueAt(0, 3).toString()+" admitidas<br>"+
                               table.getModel().getValueAt(0, 4).toString()+" omitidas<br>"+
                               table.getModel().getValueAt(0, 5).toString()+" otras<br>"+
                               "</center></html>");
        
        table = new JTable(m.consultarDenunciasPorDepartamento("MORAZAN", f.format(fecha1).toString(), f.format(fecha2).toString()));
        morazan.setText("<html><center>"+table.getModel().getValueAt(0, 0).toString()+"<br>"+
                               "denuncias: "+table.getModel().getValueAt(0, 1).toString()+"<br>"+
                               "jueces: "+table.getModel().getValueAt(0, 2).toString()+"<br>"+
                               table.getModel().getValueAt(0, 3).toString()+" admitidas<br>"+
                               table.getModel().getValueAt(0, 4).toString()+" omitidas<br>"+
                               table.getModel().getValueAt(0, 5).toString()+" otras<br>"+
                               "</center></html>");
        
        table = new JTable(m.consultarDenunciasPorDepartamento("CHALATENANGO", f.format(fecha1).toString(), f.format(fecha2).toString()));
        chalatenango.setText("<html><center>"+table.getModel().getValueAt(0, 0).toString()+"<br>"+
                               "denuncias: "+table.getModel().getValueAt(0, 1).toString()+"<br>"+
                               "jueces: "+table.getModel().getValueAt(0, 2).toString()+"<br>"+
                               table.getModel().getValueAt(0, 3).toString()+" admitidas<br>"+
                               table.getModel().getValueAt(0, 4).toString()+" omitidas<br>"+
                               table.getModel().getValueAt(0, 5).toString()+" otras<br>"+
                               "</center></html>");
        
        table = new JTable(m.consultarDenunciasPorDepartamento("USULUTAN", f.format(fecha1).toString(), f.format(fecha2).toString()));
        usulutan.setText("<html><center>"+table.getModel().getValueAt(0, 0).toString()+"<br>"+
                               "denuncias: "+table.getModel().getValueAt(0, 1).toString()+"<br>"+
                               "jueces: "+table.getModel().getValueAt(0, 2).toString()+"<br>"+
                               table.getModel().getValueAt(0, 3).toString()+" admitidas<br>"+
                               table.getModel().getValueAt(0, 4).toString()+" omitidas<br>"+
                               table.getModel().getValueAt(0, 5).toString()+" otras<br>"+
                               "</center></html>");
        
        
        }else
           JOptionPane.showMessageDialog(null, "Verifique que la fecha fin sea mayor que la fecha de inicio.");
     
 }
 
 
 
 
}
    

