/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interfaces;

import Controlador.ControladorClases;

/**
 *
 * @author Kevin
 */
public class MenuPrincipalTactico extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipalTactico
     */
    public MenuPrincipalTactico() {
        initComponents();
    }

    
        ControladorClases cc = new ControladorClases();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        frmIComparativoDeRendimiento = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        frmIExpedientesQueVenceran = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenu9 = new javax.swing.JMenu();
        frmICantidadDeDiasExpedientes = new javax.swing.JMenuItem();
        frmICantidadDeDenunciasPorJuez = new javax.swing.JMenuItem();
        frmICantidadDeJuecesPorGenero = new javax.swing.JMenuItem();
        frmICantidadDeAsignaciones = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        frmMapaDeDenuncias = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        frmRendimientoDeDepartamento = new javax.swing.JMenuItem();
        frmRendimientoDeExpedientes = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        frmPerfilDeJueces = new javax.swing.JMenuItem();
        frmPerfilDeColaboradores = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        frmGNuevoUsuario = new javax.swing.JMenuItem();
        frmGModificarUsuario = new javax.swing.JMenuItem();
        frmGConsultarUsuario = new javax.swing.JMenuItem();
        frmGEliminarUsuario = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Logo");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Informes");

        jMenu7.setText("Informes comparativos");

        frmIComparativoDeRendimiento.setText("Comparativo de rendimientos de colaboradores juridicos");
        frmIComparativoDeRendimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frmIComparativoDeRendimientoActionPerformed(evt);
            }
        });
        jMenu7.add(frmIComparativoDeRendimiento);

        jMenu2.add(jMenu7);

        jMenu8.setText("Informes de Expedientes");

        frmIExpedientesQueVenceran.setText("Expedientes que venceran en cierto periodo de tiempo");
        frmIExpedientesQueVenceran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frmIExpedientesQueVenceranActionPerformed(evt);
            }
        });
        jMenu8.add(frmIExpedientesQueVenceran);

        jMenu2.add(jMenu8);
        jMenu2.add(jSeparator1);

        jMenu9.setText("Informes de cantidad");

        frmICantidadDeDiasExpedientes.setText("Cantidad de dias de los expedientes por fases");
        frmICantidadDeDiasExpedientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frmICantidadDeDiasExpedientesActionPerformed(evt);
            }
        });
        jMenu9.add(frmICantidadDeDiasExpedientes);

        frmICantidadDeDenunciasPorJuez.setText("Cantidad de denuncias por Juez en periodos de tiempo");
        frmICantidadDeDenunciasPorJuez.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frmICantidadDeDenunciasPorJuezActionPerformed(evt);
            }
        });
        jMenu9.add(frmICantidadDeDenunciasPorJuez);

        frmICantidadDeJuecesPorGenero.setText("Cantidad de jueces procesados por genero");
        frmICantidadDeJuecesPorGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frmICantidadDeJuecesPorGeneroActionPerformed(evt);
            }
        });
        jMenu9.add(frmICantidadDeJuecesPorGenero);

        frmICantidadDeAsignaciones.setText("Cantidad de expedientes asignados a colaboradores juridicos");
        frmICantidadDeAsignaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frmICantidadDeAsignacionesActionPerformed(evt);
            }
        });
        jMenu9.add(frmICantidadDeAsignaciones);

        jMenu2.add(jMenu9);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Mapa");

        frmMapaDeDenuncias.setText("Mapa estadístico de denuncias");
        frmMapaDeDenuncias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frmMapaDeDenunciasActionPerformed(evt);
            }
        });
        jMenu4.add(frmMapaDeDenuncias);

        jMenuBar1.add(jMenu4);

        jMenu3.setText("Índices");

        frmRendimientoDeDepartamento.setText("Rendimiento del Departamento");
        frmRendimientoDeDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frmRendimientoDeDepartamentoActionPerformed(evt);
            }
        });
        jMenu3.add(frmRendimientoDeDepartamento);

        frmRendimientoDeExpedientes.setText("Rendimiento de Expedientes");
        frmRendimientoDeExpedientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frmRendimientoDeExpedientesActionPerformed(evt);
            }
        });
        jMenu3.add(frmRendimientoDeExpedientes);

        jMenuBar1.add(jMenu3);

        jMenu5.setText("Perfil");

        frmPerfilDeJueces.setText("Perfil de Jueces");
        frmPerfilDeJueces.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frmPerfilDeJuecesActionPerformed(evt);
            }
        });
        jMenu5.add(frmPerfilDeJueces);

        frmPerfilDeColaboradores.setText("Perfil de Colaboradores Jurídicos");
        frmPerfilDeColaboradores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frmPerfilDeColaboradoresActionPerformed(evt);
            }
        });
        jMenu5.add(frmPerfilDeColaboradores);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Usuarios");

        jMenu10.setText("Gestionar Usuarios");

        frmGNuevoUsuario.setText("Nuevo Usuario");
        frmGNuevoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frmGNuevoUsuarioActionPerformed(evt);
            }
        });
        jMenu10.add(frmGNuevoUsuario);

        frmGModificarUsuario.setText("Modificar datos de Usuario");
        frmGModificarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frmGModificarUsuarioActionPerformed(evt);
            }
        });
        jMenu10.add(frmGModificarUsuario);

        frmGConsultarUsuario.setText("Consultar Usuarios");
        frmGConsultarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frmGConsultarUsuarioActionPerformed(evt);
            }
        });
        jMenu10.add(frmGConsultarUsuario);

        frmGEliminarUsuario.setText("Eliminar Usuarios");
        frmGEliminarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frmGEliminarUsuarioActionPerformed(evt);
            }
        });
        jMenu10.add(frmGEliminarUsuario);

        jMenu6.add(jMenu10);

        jMenuItem5.setText("Modificar datos personales");
        jMenu6.add(jMenuItem5);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void frmIComparativoDeRendimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frmIComparativoDeRendimientoActionPerformed
        // TODO add your handling code here:

        cc.AbrirComparativoDeRendimiento();
    }//GEN-LAST:event_frmIComparativoDeRendimientoActionPerformed

    private void frmIExpedientesQueVenceranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frmIExpedientesQueVenceranActionPerformed
        // TODO add your handling code here:

        cc.AbrirExpedientesQueVenceran();
    }//GEN-LAST:event_frmIExpedientesQueVenceranActionPerformed

    private void frmICantidadDeDiasExpedientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frmICantidadDeDiasExpedientesActionPerformed
        // TODO add your handling code here:

        cc.AbrirCantidadDeDiasExpedientes();
    }//GEN-LAST:event_frmICantidadDeDiasExpedientesActionPerformed

    private void frmICantidadDeDenunciasPorJuezActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frmICantidadDeDenunciasPorJuezActionPerformed
        // TODO add your handling code here:

        cc.AbrirCantidadDeDenunciasPorJuez();

    }//GEN-LAST:event_frmICantidadDeDenunciasPorJuezActionPerformed

    private void frmICantidadDeJuecesPorGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frmICantidadDeJuecesPorGeneroActionPerformed
        // TODO add your handling code here:

        cc.AbrirCantidadDeJuecesPorGenero();
    }//GEN-LAST:event_frmICantidadDeJuecesPorGeneroActionPerformed

    private void frmICantidadDeAsignacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frmICantidadDeAsignacionesActionPerformed
        // TODO add your handling code here:

        cc.AbrirCantidadDeAsignaciones();
    }//GEN-LAST:event_frmICantidadDeAsignacionesActionPerformed

    private void frmMapaDeDenunciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frmMapaDeDenunciasActionPerformed
        // TODO add your handling code here:

        cc.AbrirMapaDeDenuncias();
    }//GEN-LAST:event_frmMapaDeDenunciasActionPerformed

    private void frmRendimientoDeDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frmRendimientoDeDepartamentoActionPerformed
        // TODO add your handling code here:

        cc.AbrirRendimientoDeDepartamento();
    }//GEN-LAST:event_frmRendimientoDeDepartamentoActionPerformed

    private void frmRendimientoDeExpedientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frmRendimientoDeExpedientesActionPerformed
        // TODO add your handling code here:

        cc.AbrirRendimientoDeExpedientes();
    }//GEN-LAST:event_frmRendimientoDeExpedientesActionPerformed

    private void frmPerfilDeJuecesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frmPerfilDeJuecesActionPerformed
        // TODO add your handling code here:

        cc.AbrirPerfilDeJueces();
    }//GEN-LAST:event_frmPerfilDeJuecesActionPerformed

    private void frmPerfilDeColaboradoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frmPerfilDeColaboradoresActionPerformed
        // TODO add your handling code here:

        cc.AbrirPerfilDeColaboradores();
    }//GEN-LAST:event_frmPerfilDeColaboradoresActionPerformed

    private void frmGNuevoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frmGNuevoUsuarioActionPerformed
        // TODO add your handling code here:

        cc.AbrirNuevoUsuario();
    }//GEN-LAST:event_frmGNuevoUsuarioActionPerformed

    private void frmGModificarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frmGModificarUsuarioActionPerformed
        // TODO add your handling code here:

        cc.AbrirModificarUsuario();
    }//GEN-LAST:event_frmGModificarUsuarioActionPerformed

    private void frmGConsultarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frmGConsultarUsuarioActionPerformed
        // TODO add your handling code here:

        cc.AbrirConsultarUsuario();
    }//GEN-LAST:event_frmGConsultarUsuarioActionPerformed

    private void frmGEliminarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frmGEliminarUsuarioActionPerformed
        // TODO add your handling code here:

        cc.AbrirEliminarUsuario();
    }//GEN-LAST:event_frmGEliminarUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalTactico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalTactico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalTactico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalTactico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipalTactico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem frmGConsultarUsuario;
    private javax.swing.JMenuItem frmGEliminarUsuario;
    private javax.swing.JMenuItem frmGModificarUsuario;
    private javax.swing.JMenuItem frmGNuevoUsuario;
    private javax.swing.JMenuItem frmICantidadDeAsignaciones;
    private javax.swing.JMenuItem frmICantidadDeDenunciasPorJuez;
    private javax.swing.JMenuItem frmICantidadDeDiasExpedientes;
    private javax.swing.JMenuItem frmICantidadDeJuecesPorGenero;
    private javax.swing.JMenuItem frmIComparativoDeRendimiento;
    private javax.swing.JMenuItem frmIExpedientesQueVenceran;
    private javax.swing.JMenuItem frmMapaDeDenuncias;
    private javax.swing.JMenuItem frmPerfilDeColaboradores;
    private javax.swing.JMenuItem frmPerfilDeJueces;
    private javax.swing.JMenuItem frmRendimientoDeDepartamento;
    private javax.swing.JMenuItem frmRendimientoDeExpedientes;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
