/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interfaces;

import Clases.Juridico;
import Controlador.ControladorClases;
import Controlador.Validar;
import Controlador.VariablesGlobales;
import java.sql.Connection;
import java.sql.DriverManager;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JTable;

import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRExporter;
import net.sf.jasperreports.engine.JRExporterParameter;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.export.JRHtmlExporter;
import net.sf.jasperreports.engine.export.JRPdfExporter;
import net.sf.jasperreports.engine.export.JRXlsExporter;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author Kevin
 */
public class PerfilDeColaboradores extends javax.swing.JFrame {

    public int IDJURIDICO=1;
    public int ANIO=2005;
    PerfilDeColaboradoresParametros pcj = new PerfilDeColaboradoresParametros();
    public boolean reporte=false;
    
    /**
     * Creates new form PerfilDeColaboradores
     */
    public PerfilDeColaboradores() {
        initComponents();
        pcj.setVisible(true);
        pcj.setLocationRelativeTo(null);
        pcj.requestFocus();
        
        
             
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_IDJURIDICO = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField_NOMBRE = new javax.swing.JTextField();
        jTextField_APELLIDO = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField_EXPEDIENTES = new javax.swing.JTextField();
        jTextField_EXPEDIENTESFINALIZADOS = new javax.swing.JTextField();
        jTextField_ANIO = new javax.swing.JTextField();
        jTextField_EXPEDIENTESPENDIENTES = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PERFIL");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        jLabel11.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Foto");
        jLabel11.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.gray));
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 140, 157));

        jLabel2.setFont(new java.awt.Font("Cambria", 2, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/search icon.png"))); // NOI18N
        jLabel2.setText("Id Jurídico:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, -1, -1));

        jTextField_IDJURIDICO.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        getContentPane().add(jTextField_IDJURIDICO, new org.netbeans.lib.awtextra.AbsoluteConstraints(515, 40, 90, -1));

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel3.setText("Nombres");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel4.setText("Apellidos");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, -1, -1));

        jTextField_NOMBRE.setEditable(false);
        jTextField_NOMBRE.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        getContentPane().add(jTextField_NOMBRE, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 250, -1));

        jTextField_APELLIDO.setEditable(false);
        jTextField_APELLIDO.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        getContentPane().add(jTextField_APELLIDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 250, -1));

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel5.setText("Cantidad de expedientes asignados");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, -1));

        jLabel6.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel6.setText("Cantidad de expedientes finalizados");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, -1));

        jLabel7.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel7.setText("Cantidad de expedientes que no procedieron");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, -1, -1));

        jLabel8.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel8.setText("Año");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, -1, -1));

        jTextField_EXPEDIENTES.setEditable(false);
        jTextField_EXPEDIENTES.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        getContentPane().add(jTextField_EXPEDIENTES, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, 150, -1));

        jTextField_EXPEDIENTESFINALIZADOS.setEditable(false);
        jTextField_EXPEDIENTESFINALIZADOS.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        getContentPane().add(jTextField_EXPEDIENTESFINALIZADOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, 150, -1));

        jTextField_ANIO.setEditable(false);
        jTextField_ANIO.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        getContentPane().add(jTextField_ANIO, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, 150, -1));

        jTextField_EXPEDIENTESPENDIENTES.setEditable(false);
        jTextField_EXPEDIENTESPENDIENTES.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        getContentPane().add(jTextField_EXPEDIENTESPENDIENTES, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 150, -1));

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/little logo.png"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 63, 67));

        jSeparator1.setFont(new java.awt.Font("Cambria", 0, 11)); // NOI18N
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 210, 10));

        jLabel10.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("COLABORADOR JURÍDICO");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));

        jLabel9.setBackground(new java.awt.Color(47, 72, 85));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/top.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 70));
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 590, 10));

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(521, 330, 80, -1));

        jButton2.setText("Consultar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 370, -1, -1));

        jButton3.setText("Informe");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(521, 410, 80, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       /* boolean validarJ = false;
        boolean validarA = false;
        Validar v = new Validar();
        
        Juridico juridico = new Juridico();
        
        try{
            
        this.IDJURIDICO= Integer.parseInt(JOptionPane.showInputDialog("Ingrese el ID del juridico:"));
        if(IDJURIDICO<0){
        this.IDJURIDICO= Integer.parseInt(JOptionPane.showInputDialog("El ID del juridico debe ser mayor a 1"));
        }else{
         validarJ = true;   
        }
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Error. El ID del juridico debe ser un numero");
        }
        
        try{
            this.ANIO= Integer.parseInt(JOptionPane.showInputDialog("Ingrese el año a consultar (desde 1995 hasta la fecha):"));
            
            if(ANIO<1995 && ANIO > 2015){
            this.ANIO= Integer.parseInt(JOptionPane.showInputDialog("Error. El año debe estar entre 1995 hasta 2015:"));
            }else{
                validarA = true;
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Error. El Año debe ser numerico desde 1995");
        }
        if(validarJ && validarA){
        JTable jTBL = new JTable(juridico.consultarJuridico(this.IDJURIDICO, this.ANIO));
        if(jTBL.getRowCount()==1){
        jTextField_IDJURIDICO.setText((String)jTBL.getModel().getValueAt(0, 0));
        jTextField_NOMBRE.setText((String)jTBL.getModel().getValueAt(0, 1));
        jTextField_APELLIDO.setText((String)jTBL.getModel().getValueAt(0, 2));
        jTextField_EXPEDIENTES.setText((String)jTBL.getModel().getValueAt(0, 3));
        jTextField_EXPEDIENTESFINALIZADOS.setText((String)jTBL.getModel().getValueAt(0, 4));
        jTextField_EXPEDIENTESPENDIENTES.setText((String)jTBL.getModel().getValueAt(0, 5));
        jTextField_ANIO.setText(Integer.toString(this.ANIO));                 
                
        }else{
            JOptionPane.showMessageDialog(rootPane, "Juez no encontrado");
            }
        }*/
        
        
        Juridico juridico = new Juridico();
        this.IDJURIDICO=Integer.parseInt(VariablesGlobales.VARAUX1);
        this.ANIO=Integer.parseInt(VariablesGlobales.VARAUX2);
        JTable jTBL = new JTable(juridico.consultarJuridico(this.IDJURIDICO, this.ANIO));
        jTextField_IDJURIDICO.setText((String)jTBL.getModel().getValueAt(0, 0));
        jTextField_NOMBRE.setText((String)jTBL.getModel().getValueAt(0, 1));
        jTextField_APELLIDO.setText((String)jTBL.getModel().getValueAt(0, 2));
        jTextField_EXPEDIENTES.setText((String)jTBL.getModel().getValueAt(0, 3));
        jTextField_EXPEDIENTESFINALIZADOS.setText((String)jTBL.getModel().getValueAt(0, 4));
        jTextField_EXPEDIENTESPENDIENTES.setText((String)jTBL.getModel().getValueAt(0, 5));
        jTextField_ANIO.setText(Integer.toString(this.ANIO)); 
        reporte=true;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        ControladorClases cc = new ControladorClases();
        cc.AbrirPerfilDeColaboradores();
        this.dispose();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        try{
            if(reporte){
            
            //conectandose a la base
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://"+VariablesGlobales.serverName+":"+VariablesGlobales.tcpip+";database=BDSIGCSJ;integratedSecurity=true;";
            Connection cn = DriverManager.getConnection(url);
            
            //proceso de jasper report---------------------------------------------------------------------------
            JasperReport jreport = (JasperReport) JRLoader.loadObjectFromFile("PerfilColaborador.jasper");
            Map parametros = new HashMap();
            parametros.put("autor", VariablesGlobales.NOMBREUSUARIO); //metiendo variables
            parametros.put("IDJURIDICO", Integer.parseInt(jTextField_IDJURIDICO.getText())); //metiendo variables
            parametros.put("ANIO", Integer.parseInt(jTextField_ANIO.getText())); //metiendo variables
            JasperPrint jasperPrint = JasperFillManager.fillReport(jreport, parametros, cn);
            JasperViewer ventanavisor = new JasperViewer(jasperPrint, false);
            ventanavisor.setTitle("CORTE SUPREMA DE JUSTICIA");
            ventanavisor.setVisible(true);    
            //fin proceso jasper ---------------------------------------------------------------------------------
            
            }else{
                JOptionPane.showMessageDialog(null, "Para generar un reporte primero oprima el Aceptar");
            }
        }catch(Exception e){
            
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PerfilDeColaboradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PerfilDeColaboradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PerfilDeColaboradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PerfilDeColaboradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PerfilDeColaboradores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField_ANIO;
    private javax.swing.JTextField jTextField_APELLIDO;
    private javax.swing.JTextField jTextField_EXPEDIENTES;
    private javax.swing.JTextField jTextField_EXPEDIENTESFINALIZADOS;
    private javax.swing.JTextField jTextField_EXPEDIENTESPENDIENTES;
    private javax.swing.JTextField jTextField_IDJURIDICO;
    private javax.swing.JTextField jTextField_NOMBRE;
    // End of variables declaration//GEN-END:variables
}
